name: RKE-E2E-TESTS-POC

on:
  workflow_dispatch:
  schedule:
     #Runs "every hour" (see https://crontab.guru)
    - cron: "0 */1 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade packages
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: Write the cypress.env.json file
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > Cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.7
        with:
          install: false
          browser: chrome
          headed: false
          env: true
        env:
          client_id: ${{ secrets.CYPRESS_PT_CLIENT_ID }}
          CYPRESS_PTauthUrl: ${{ secrets.CYPRESS_PT_AUTH_URL }}
          client_secret: ${{ secrets.CYPRESS_PT_CLIENT_SECRET }}
          username: ${{ secrets.CYPRESS_PT_USER_NAME }}
          password: ${{secrets.CYPRESS_PT_PASSWORD }}      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_TITLE: END TO END TESTS REPORT
          SLACK_MESSAGE: "THIS IS THE END TO END TEST REPORT:rocket"
      


    
