name: RKE-E2E-TESTS-POC

on:
  workflow_dispatch:
  schedule:
     #Runs "every hour" (see https://crontab.guru)
    - cron: "0 */1 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade packages
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.7
        with:
          install: false
          browser: chrome
          headed: false
        env:
          CYPRESS_PTClientID: ${{ secrets.PT_CLIENT_ID }}
          CYPRESS_PTauthUrl: ${{ secrets.PT_AUTH_URL }}
          CYPRESS_PTClientSecret: ${{ secrets.PT_CLIENT_SECRET }}
          CYPRESS_PTusername: ${{ secrets.PT_USER_NAME }}
          CYPRESS_PTpassword: ${{secrets.PT_PASSWORD }}      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_TITLE: END TO END TESTS REPORT
          SLACK_MESSAGE: "THIS IS THE END TO END TEST REPORT:rocket"
      


    
