name: RKE-E2E-TESTS-POC

on:
  schedule: 
# Runs "at 06:00  every day" (see https://crontab.guru)
    - cron: '0 */6 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome105-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: false
	env:
          HUB_AUTH_TOKEN: ${{ secrets.HUB_AUTH_TOKEN }}
          HUB_BASE_URL: ${{ secrets.HUB_BASE_URL }}
          HUB_PROJECTUID: ${{ secrets.HUB_PROJECTUID }}
          TEST_NODE_ID: ${{ secrets.TEST_NODE_ID }}
	  run-name: ${{ secrets.TEST1_NODE_ID }}
	
	 
	  
			 
		
            
           
