name: Cypress Cucumber Test Example

on:
  schedule: 
# Runs "at 06:00  every day" (see https://crontab.guru)
    - cron: '0 */6 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome105-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: false
	env:
          PT_CLIENT_ID: ${{ secrets.PT_CLIENT_ID }}
          PT_AUTH_URL: ${{ secrets.PT_AUTH_URL }}
          PT_CLIENT_SECRET: ${{ secrets.PT_CLIENT_SECRET }}
          PT_USER_NAME: ${{ secrets.PT_USER_NAME }}
	 
	  
			 
		
            
           
