name: RKE-E2E-TESTS-POC

on:
  workflow_dispatch:
  schedule:
     #Runs "every midnight" (see https://crontab.guru)
    - cron: "0 0 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade packages
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: create the cypress.env.json file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.CYPRESS_ENV_CI }}
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        #run: |
         # echo ${{ secrets.CYPRESS_ENV_CI }} | base64 -d > Cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.7
        with:
          install: false
          browser: chrome
          headed: false
          command: |
            npx cypress run 
            
      - name: Slack Notification
        runs-on: ubuntu-latest
        needs: Cypress run
        steps:
          - name: Download test artifacts
            uses: actions/download-artifact@v3
            with:
              path: test-artifacts
      - name: 'Send Slack notification'
        uses: automattic/action-test-results-to-slack@v1
        with:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_TITLE: END TO END TESTS REPORT
          SLACK_MESSAGE: "THIS IS THE END TO END TEST REPORT:rocket"
                
          
        # uses: rtCamp/action-slack-notify@v2
        # env:
        #   SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
        #   SLACK_TITLE: END TO END TESTS REPORT
        #   SLACK_MESSAGE: "THIS IS THE END TO END TEST REPORT:rocket"
      
      


# name: 'Send Slack notification'
#     runs-on: ubuntu-latest
#     needs: run-tests
  
#     steps:
#       - name: Download test artifacts
#         uses: actions/download-artifact@v3
#         with:
#           path: test-artifacts

#       - name: 'Send Slack notification'
#         uses: automattic/action-test-results-to-slack@v1
#         with:







    
