

on: workflow_dispatch
    
name: End to End test report
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: END TO END TESTS REPORT
        SLACK_MESSAGE: "THIS IS THE END TO END TEST REPORT:rocket"
      
