name: Cypress Tests

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
  schedule:
     #Runs "every midnight" (see https://crontab.guru)
    - cron: "0 0 * * *"

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: create the cypress.env.json file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.CYPRESS_ENV_CI }}

      - name: Cypress run with Slack reporting
        run: |
          npx cypress run --reporter cypress-slack-reporter
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}