name: RKE-E2E-SMOKE-TESTS

on:
  workflow_dispatch:
  schedule:
     #Runs "every 15 minutes" (see https://crontab.guru)
    - cron: "*/15 * * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
             node-version: latest
      - name: Upgrade packages
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: create the cypress.env.json file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.CYPRESS_ENV_CI }}
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.7
        with:
          install: false
          browser: chrome
          headed: false
          command: npm run testH
      - name: uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/cucumber-html/test-report.html
          retention-days: 10
      - name: Report Status to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: Rke-e2e-smoke-test-report
          footer: "<{run_url}|View Run>|Linked Repo <{repo_url}|View Workflow>|This job runs every 15 minutes"
        env:
          SLACK_WEBHOOK_URL:  ${{secrets.SLACK_WEBHOOK}}
      # - name: Upload report to slack step
      #   uses: adrey/slack-file-upload-action@1.0.5
      #   with:
      #     token: ${{secrets.SLACK_TOKEN}}
      #     path: cypress/reports/cucumber-html/test-report.html
      #     channel: ce-rke-e2e-test-run-alerts
          
