name: RKE-E2E-TESTS-POC

on:
  workflow_dispatch:
  schedule:
     #Runs "every two hours" (see https://crontab.guru)
    - cron: "0 */2 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade packages
        run: npm install @badeball/cypress-cucumber-preprocessor
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: create the cypress.env.json file
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.CYPRESS_ENV_CI }}
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.7
        with:
          install: false
          browser: chrome
          headed: false
          command: npm run testH
      - name: uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/cucumber-html/test-report.html
          retention-days: 10
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_USERNAME: Smoke Test BOT
          SLACK_TITLE: Smoke Test 
          SLACK_MESSAGE: "Results From Smoke Test :rocket:"
          SLACK_COLOR: ${{ job.status }}
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'success,failure'
          notification_title: Rke-e2e-smoke-test-report
          footer: <***run_url***|View Run> | This job Runs Every Two hours 
        env:
          SLACK_WEBHOOK_URL:  ${{secrets.SLACK_WEBHOOK}}
